trigger: none
schedules:
  - cron: "0 * * * *" # Optional hourly trigger
    displayName: Hourly check
    branches:
      include: [ main ]
    always: true

jobs:
  - job: CheckForTasks
    pool:
      vmImage: 'ubuntu-latest' # Or self-hosted with preinstalled tools
    steps:
      - checkout: self

      - task: PythonScript@0
        displayName: 'Check for New Tasks'
        inputs:
          scriptSource: 'filePath'
          scriptPath: 'check_for_tasks.py'
        env:
          AZURE_DEVOPS_ORG: tlaukkanen
          AZURE_DEVOPS_PROJECT: simple-to-do
          AZURE_DEVOPS_PAT: $(System.AccessToken)

      - script: |
          echo "##vso[task.setvariable variable=TASK_ID;isOutput=true]$(cat task_id.txt)"
          echo "Task ID set to: $(cat task_id.txt)"
        displayName: 'Set Task ID Variable'

  - job: RunAIAgent
    dependsOn: CheckForTasks
    variables:
      TASK_ID: $[ dependencies.CheckForTasks.outputs['task_id'] ]
    # This job runs only if a new task is found and is not zero
    condition: and(succeeded(), or(ne(variables['TASK_ID'], '0'), ne(variables['TASK_ID'], '')))
    pool:
      vmImage: 'ubuntu-latest' # Or self-hosted with preinstalled tools
    steps:
      - checkout: self

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.10'

      - script: |
          pip install -r requirements.txt
          python ai_agent_runner.py
        displayName: 'Run LangChain AI Agent'

      - script: |
          git config user.email "ai-bot@example.com"
          git config user.name "AI Bot"
          git checkout -b ai/task-${TASK_ID}
          git add .
          git commit -m "Auto-implemented task ${TASK_ID}"
          git push origin ai/task-${TASK_ID}
        displayName: 'Commit & Push Changes'

      - script: |
          python create_pull_request.py ${TASK_ID}
        displayName: 'Create Pull Request'
