trigger: none
# schedules:
#   - cron: "0 * * * *" # Optional hourly trigger
#     displayName: Hourly check
#     branches:
#       include: [ main ]
#     always: true

resources:
  repositories:
    - repository: self
      type: git
      name: devops-ai-developer
      ref: refs/heads/main
      trigger: none
    - repository: simple-to-do
      type: git
      name: simple-to-do
      ref: refs/heads/main
      trigger: none

jobs:
  - job: CheckForTasks
    pool:
      vmImage: 'ubuntu-latest' # Or self-hosted with preinstalled tools
    steps:
      - checkout: self

      - checkout: simple-to-do
        path: 'simple-to-do'
        displayName: 'Checkout simple-to-do repository'

      - task: PythonScript@0
        displayName: 'Check for New Tasks'
        inputs:
          scriptSource: 'filePath'
          scriptPath: 'check_for_tasks.py'
        env:
          AZURE_DEVOPS_ORG: tlaukkanen
          AZURE_DEVOPS_PROJECT: simple-to-do
          AZURE_DEVOPS_PAT: $(System.AccessToken)

      - script: |
          echo "##vso[task.setvariable variable=TaskId;isOutput=true]$(cat task_id.txt)"
          echo "Task ID set to: $(cat task_id.txt)"
        displayName: 'Set Task ID Variable'
        name: SetTaskId

  - job: RunAIAgent
    dependsOn: CheckForTasks
    variables:
      - name: TaskId
        value: $[ dependencies.CheckForTasks.outputs['SetTaskId.TaskId'] ]
    # This job runs only if a new task is found and is not zero
    condition: and(succeeded(), and(dependencies.CheckForTasks.outputs['SetTaskId.TaskId'], ne(dependencies.CheckForTasks.outputs['SetTaskId.TaskId'], '0')))
    pool:
      vmImage: 'ubuntu-latest' # Or self-hosted with preinstalled tools
    steps:
      - checkout: self

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.12'

      - script: |
          pip install uv
          uv sync
          uv run ai_agent_runner.py $(TaskId) --codebase-path simple-to-do
        displayName: 'Run LangChain AI Agent'
        env:
          AZURE_DEVOPS_ORG: tlaukkanen
          AZURE_DEVOPS_PROJECT: simple-to-do
          AZURE_DEVOPS_PAT: $(System.AccessToken)
          AZURE_OPENAI_API_KEY: $(AZURE_OPENAI_API_KEY)
          AZURE_OPENAI_ENDPOINT: $(AZURE_OPENAI_ENDPOINT)

      # - script: |
      #     git config user.email "ai-bot@example.com"
      #     git config user.name "AI Bot"
      #     git checkout -b ai/task-${TASK_ID}
      #     git add .
      #     git commit -m "Auto-implemented task ${TASK_ID}"
      #     git push origin ai/task-${TASK_ID}
      #   displayName: 'Commit & Push Changes'

      # - script: |
      #     python create_pull_request.py ${TASK_ID}
      #   displayName: 'Create Pull Request'
