trigger: none
schedules:
  - cron: "0 6 * * *" # Optional daily trigger at 6 AM
    displayName: Daily sync
    branches:
      include: [ main ]
    always: true

jobs:
  - job: SyncFromGitHub
    pool:
      vmImage: 'ubuntu-latest' # Or self-hosted with preinstalled tools
    steps:
      - checkout: self

      # Synchronize code from GitHub repository to this repository in Azure DevOps
      # git@github.com:tlaukkanen/devops-ai-developer.git
      - script: |
          git remote add github git@github.com:tlaukkanen/devops-ai-developer.git
          git fetch github
          git reset --hard github/main
          git push origin main --force
        displayName: 'Sync from GitHub'