trigger: none
schedules:
  - cron: "0 6 * * *" # Optional daily trigger at 6 AM
    displayName: Daily sync
    branches:
      include: [ main ]
    always: true

jobs:
  - job: SyncFromGitHub
    pool:
      vmImage: 'ubuntu-latest' # Or self-hosted with preinstalled tools
    steps:
      - checkout: self

      # Synchronize code from GitHub repository to this repository in Azure DevOps
      # git@github.com:tlaukkanen/devops-ai-developer.git
      - script: |
          git config user.email "ai-developer@codeof.me"
          git config user.name "DevOps AI Developer"
          git remote remove github || true
          # Add GitHub remote and fetch latest changes
          git remote add github https://github.com/tlaukkanen/devops-ai-developer.git
          git fetch github
          git checkout -B main github/main
          git push origin main --force
        displayName: 'Sync from GitHub'